FROM iojs:onbuild

COPY ./program.js ./program.js
COPY ./package.json ./package.json
COPY ./entrypoint_background.sh ./entrypoint_background.sh

RUN chmod a+x ./entrypoint_background.sh

EXPOSE 3000

ENTRYPOINT ["./entrypoint_background.sh"]
